# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Our Navy Portal (Project Waterfall)
email: michael.pyne@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is a working prototype for what a military HR portal useful to US Navy
  Sailors could work like, if it were also highly performant.

  All things here are completely unofficial, not endorsed by the US Navy, US
  Department of Defense, or anyone else. Do not use this to setup for your next
  CDB. :P
baseurl: "/proj-waterfall" # the subpath of your site, e.g. /blog
url: "https://mpyne-navy.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: mpyne-navy

# Build settings
markdown: kramdown
theme: minima
plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
# - Gemfile
# - Gemfile.lock
# - node_modules
# - vendor/bundle/
# - vendor/cache/
# - vendor/gems/
# - vendor/ruby/
